# Generated by Django 2.0.5 on 2018-05-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20180526_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploadfile/%Y/%m/%d/content', verbose_name='이미지 파일'),
        ),
    ]
